_target_: shac.algorithms.ahac.AHAC
_recursive_: False
actor_config:
  _target_: shac.models.actor.ActorStochasticMLP
  units: ${resolve_child:[64,64],${env.shac.actor_mlp},units}
  activation: elu
critic_config:
  _target_: shac.models.critic.DoubleCriticMLP
  units: ${resolve_child:[64,64],${env.shac.critic_mlp},units}
  activation: elu
actor_lr: 1e-4
critic_lr: 2e-4
lambd_lr: 5e-4
contact_threshold: 500
lr_schedule: linear
obs_rms: True
ret_rms: False
critic_iterations: 16  # if not specified will do early stopping
critic_batches: 4
critic_method: td-lambda # ('td-lambda', 'one-step')
lam: 0.95
gamma: 0.99
max_epochs: ${resolve_child:100,${env.shac},max_epochs}  # کاهش تعداد اپوک‌ها
steps_min: 1
steps_max: 30
grad_norm: 1.0
save_interval: ${resolve_child:400,${env.shac},save_interval}
stochastic_eval: False
eval_runs: 30
train: ${general.train}
device: ${general.device}

