name: env_webot
config:
  _target_: AHACEnvWrapper.AHACEnvWrapper
  no_grad: True

shac:
  actor_lr: 1e-4
  critic_lr: 2e-4
  max_epochs: 64
  save_interval: 128
  target_critic_alpha: 0.99
  actor_mlp:
    units: [400, 200, 100]
  critic_mlp:
    units: [400, 200, 100]

ppo:
  max_epochs: 50000
  lr: 5e-4
  minibatch_size: 16384
  num_actors: 2048
  horizon_length: 32
  save_frequency: 500
  save_best_after: 500
  actor_mlp:
    units: [400, 200, 100]

sac:
  max_epochs: 5000
  batch_size: 4096
  num_actors: 128
  save_frequency: 500
  save_best_after: 500
  actor_critic_mlp:
    units: [128, 64, 32]

# Note SVG doesn't like floats so we use ints
svg:
  num_train_steps: 11000000 # 11M
  replay_buffer_capacity: 1000000
